config/routes.rb
Rails.application.routes.draw do

  ########################################
  # SUPER
  ########################################

  constraints host: ENV['SUPER_HOST'] do
    scope module: :super do
      resources :foobars
      get '/' => 'super#index'

    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  resources :posts do
    # resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:index, :create, :destroy], module: :posts
    resource :like, module: :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes

  mount_uploader :image, ImageUploader

  validates :image, file_size: { less_than: 5.megabytes }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes

  def likes?(post)
    post.likes.where(user_id: id).any?
  end


  # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))

    if @comment.save
      redirect_to post_path(@post)
    end

  end

  def update
  end

  def destroy
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end
  
  private
    def set_post
      @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image, :remove_image, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>

  <p class="comment-header">
    <%= comment.user.name %>
  </p>
  <p>
    <%= time_ago_in_words(comment.created_at) %>Ago
  </p>
  <p>
    <%= comment.body %>
  </p>

<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  
  <%= f.text_area :body, placeholder: "Comment" %>
  <%= f.submit 'Submit', :class => 'btn'%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <br />
  <br />

  <%= f.label :body %>
  <%= f.text_area :body %>

  <br />
  <br />

  <% if @post.image? %>
    <%= image_tag @post.image.thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= f.check_box :remove_image %>
      <% end %>
    </div>
  <% end %>

  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>

  <%= f.submit 'Submit' %>

<% end %>

app/views/posts/_likes.html.erb
<% if user_signed_in? && current_user.likes?(@post) %>
  <%= link_to "Unlike", post_like_path(@post), method: :delete, remote: true  %>
<% else %>
  <%= link_to "Like", post_like_path(@post), method: :post, remote: true %>
<% end %>

<%= @post.likes.count %>

<% @post.likes.each do |like| %>
  <%= image_tag like.user.avatar, width: 20  %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit!</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Post!</h1>

<% if user_signed_in? %>
  <%= link_to 'Edit Profile', edit_user_registration_path %><br />
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<% else %>
  <%= link_to('Sign Up', new_user_registration_path) %><br />
  <%= link_to('Login', new_user_session_path) %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% @posts.each do |post| %>

  <h2>
    <%= link_to post.title, post %>
  </h2>

  <p>
    <%= post.body %>
  </p>
  <p>
    <%= post.created_at.strftime("%B, %d, %Y") %>
  </p>

  <p>
    <%= post.user.name %>
    <%= link_to(image_tag(post.user.avatar.thumb.url, alt: 'Avatar'), post.user.avatar.url, target: '_blank') if post.user.avatar? %>
  </p>

<% end %>
<br />
<p>
  <%= link_to "Create a new post", new_post_path %>
</p>

app/views/posts/likes/create.js.erb
$("#likes").html("<%= j render partial: 'posts/likes' %>");

app/views/posts/likes/destroy.js.erb
$("#likes").html("<%= j render partial: 'posts/likes' %>");

app/views/posts/new.html.erb
<h2>Create a New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to "Back to Posts", posts_path %>

<h2>Title</h2>
<p>
  <%= @post.title %>
</p>

<h2>Body</h2>
<p>
  s
  <%= @post.body %>
</p>

<p>
  <%= @post.created_at.strftime("%B, %d, %Y") %>
</p>

<div id="likes">
  <%= render partial: "likes" %>
</div>

<%= link_to "Edit Posts", edit_post_path(@post) %><br />
<%= link_to "Delete Posts", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>


<h2>Comments</h2>
<%= render 'comments/comment' %>

<h2>Add a Comment:</h2>
<%= render 'comments/form' %>

app/views/super/foobars/_form.html.erb
<%= form_with(model: foobar, local: true) do |form| %>
  <% if foobar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foobar.errors.count, "error") %> prohibited this foobar from being saved:</h2>

      <ul>
      <% foobar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :foobar_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/super/foobars/edit.html.erb
<h1>Editing Foobar</h1>

<%= render 'form', foobar: @foobar %>

<%= link_to 'Show', @foobar %> |
<%= link_to 'Back', foobars_path %>

app/views/super/foobars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foobars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foobars.each do |foobar| %>
      <tr>
        <td><%= foobar.name %></td>
        <td><%= link_to 'Show', foobar %></td>
        <td><%= link_to 'Edit', edit_foobar_path(foobar) %></td>
        <td><%= link_to 'Destroy', foobar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foobar', new_foobar_path %>

app/views/super/foobars/new.html.erb
<h1>New Foobar</h1>

<%= render 'form', foobar: @foobar %>

<%= link_to 'Back', foobars_path %>

app/views/super/foobars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foobar.name %>
</p>

<%= link_to 'Edit', edit_foobar_path(@foobar) %> |
<%= link_to 'Back', foobars_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>